version: "3" 

services:


    app:
        build:
            context: flask
        volumes: 
            - ./flask:/app
        environment: 
            - FLASK_APP=run_app.py
        ports:
            - "5000"

    web_server: 
        image: nginx:1.21.6-alpine
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        ports: 
            - "80:80"
